### ISSUE TITLE
Compilation and Test status

### ISSUE THREAD

**Issue by Stagge** [DD2480-Group-23/Group23-CI#9]
The server's console should state information about compilation and testing of the affected branch when a webhook triggers.

Server console output should inculde:
- What branch triggered the webhook, and what user made the commit (this information should be available in the payload JSON)
- Whether the compilation of the project succeeded.
- Testing information (Number of Tests run, and number of tests failed)

Compilation and testing information of the build is right now printed to the output.txt.

**Comment by BDidace** [comment]
The first point is done, the server's console now states information about what branch triggered the webhook, and what user made the commit.
